Add a few missing defines
Weirdly, these had been there before.

../../../../download/rtl8812au/hal/rtl8814a/rtl8814a_hal_init.c:3407:24: error: ‘MACID_NUM_8814A’ undeclared (first use in this function); did you mean ‘MAC_REG_NUM_8814’?
 3407 |  hal_spec->macid_num = MACID_NUM_8814A;
      |                        ^~~~~~~~~~~~~~~
      |                        MAC_REG_NUM_8814
../../../../download/rtl8812au/hal/rtl8814a/rtl8814a_hal_init.c:3408:30: error: ‘SEC_CAM_ENT_NUM_8814A’ undeclared (first use in this function)
 3408 |  hal_spec->sec_cam_ent_num = SEC_CAM_ENT_NUM_8814A;
      |                              ^~~~~~~~~~~~~~~~~~~~~
../../../../download/rtl8812au/hal/rtl8814a/rtl8814a_hal_init.c:3417:23: error: ‘BAND_CAP_8814A’ undeclared (first use in this function); did you mean ‘BAND_CAP_2G’?
 3417 |  hal_spec->band_cap = BAND_CAP_8814A;
      |                       ^~~~~~~~~~~~~~
      |                       BAND_CAP_2G
../../../../download/rtl8812au/hal/rtl8814a/rtl8814a_hal_init.c:3418:21: error: ‘BW_CAP_8814A’ undeclared (first use in this function); did you mean ‘RWCAM_8814A’?
 3418 |  hal_spec->bw_cap = BW_CAP_8814A;
      |                     ^~~~~~~~~~~~
      |                     RWCAM_8814A